### PR TITLE
adding to -detach to help with the workshop flow

### PR DESCRIPTION
**Pull request by gitrgoliveira**

### CODE REVIEW

**Review by rberlind — COMMENTED** [review]
@gitrgoliveira : I had added `-detach` to the solve scripts.  But is it also needed in the instructions in the assignment?  Using it would not be a normal thing to do.  Users who don't want to wait for the monitoring to complete can just do `<control>-c`

**Comment by gitrgoliveira** [comment]
ctrl-c didn't work for me. I'll try the same track again.
Because these are waiting for a promotion, the `nomad job run` command gets stuck.

**Comment by rberlind** [comment]
@gitrgoliveira : are you using a Mac or a PC?

**Comment by rberlind** [comment]
I concur that ctrl-c is no longer working but I think this is due to the changes that Instruqt made today.  I also see a strange rectangular cursor flickering while the `nomad job run` command is monitoring the deployment.  I reported these problems to Instruqt.  Rather than changing the command we tell the user to run, I would rather wait to see if Instruqt can fix the problem so that ctrl-c will work.  We can then tell the user to use that in the assignment.

**Comment by gitrgoliveira** [comment]
ctrl+c seems to be working now.

**Pull request closed without merging**
